- Cargo.toml
- src/immutable_data.rs
- src/lib.rs
- src/response.rs
Define required types inline and use bincode for serialisation.
> Get rid of routing and maidsafe_utils dependencies

- src/appendable_data.rs
- src/errors.rs
- src/lib.rs
- src/mutable_data.rs
- src/request.rs
This PR implements some of the `AppendOnlyData` functions as they are described in the RFC.
Currently, it lacks the permissions handling and response types.
> Implement the basic functions of AppendOnlyData

- src/lib.rs
- src/mutable_data.rs
- src/request.rs
- src/response.rs
- Introduce MutableData enum to group sequenced and unsequenced types
- Add variants to Request and Reseponse to handle more RPCs for MData
operations
> Introduce MData enum and add more RPCs

- src/identity/client.rs
- src/public_key.rs
Hash, Ord, and PartialOrd are now implemented for `safe_nd::PublicKey` and
`safe_nd::identity::client::PublicId`.
> Implement more traits for public ID

- .travis.yml
- Dockerfile.build
- Jenkinsfile
- Makefile
This adds a Jenkins build for safe-nd. Right now it's just a simple one stage pipeline with build and test. We can expand as needed.
It also removes the macOS and Windows builds because these are now covered by Jenkins. Linux on Travis is retained for open source alignment.
> Jenkins Build

- Cargo.toml
- src/append_only_data.rs
- src/lib.rs
- src/mutable_data.rs
- src/public_key.rs
- src/request.rs
Requester has been made redundant with the change in the way we approach permissions handling client/app keys. This PR also exposes some of the necessary symbols from internal modules and fixes the `threshold_crypto` dependency.
> Remove Requester and overhaul perms handling

- Cargo.toml
- src/append_only_data.rs
- src/coins.rs
- src/errors.rs
- src/identity/app.rs
- src/identity/client.rs
- src/identity/mod.rs
- src/identity/node.rs
- src/immutable_data.rs
- src/lib.rs
- src/mutable_data.rs
- src/public_key.rs
- src/request.rs
- src/response.rs
- src/utils.rs
Resolves issue #44 
- Removed base64 crate from dependencies
- Added utils module containing wrappers for serialization and encode/decode
- Changed all occurrences of previous base64 encode/decode to the new z-base-32 encode/decode 
wrappers
- Implemented encode/decode helper functions and tests for Xorname, PublicKey, 
AppPublicId,ClientPublicId, NodePublicId, PublicId, ADataAddress, IDataAddress, MDataAddress
This commit also includes a minor refactor for AppendOnly Data
- Moved AData impl from requests module to append_only_data module
- Introduced two macros to reduce LOC
- Moved permissions checking from types to AData enum
- Refactored return type for in_range function
> refactor/encode: introduces multibase z-base-32 encode/decode by swapping base64 encode/decode

- src/errors.rs
- src/lib.rs
- src/request.rs
- src/request/account_data.rs
- src/response.rs
Instead of a single PutAccount RPC, we now have `CreateAccount`, `CreateAccountFor`, and `UpdateAccount`. `CreateAccountFor` is required for the case when a user asks a third party to create a new coin balance _and_ a new account for them.
> Change PutAccount RPC

- src/append_only_data.rs
- src/immutable_data.rs
- src/lib.rs
- src/mutable_data.rs
- src/request.rs
- src/response.rs
Addresses this [forum feedback](https://safenetforum.org/t/rfc-54-published-and-unpublished-datatype/28620/17), and makes the data types easier to work with in SCL (based on inefficiencies I noticed while working with the new MData types in https://github.com/maidsafe/safe_client_libs/issues/814).
> refactor/data: refactor data types

- Dockerfile.build
This synchronises the IDs with the IDs of the `jenkins` user on the build slave. This should hopefully reduce the Linux build time quite significantly, because it avoids having to change permissions for thousands of files (this is a classic problem with Docker - details [here](https://boxboat.com/2017/07/25/fixuid-change-docker-container-uid-gid/) if you're interested). The external disks used by machines on AWS are quite slow, so changing all the permissions can take 5 - 10 minutes sometimes.
Once this is merged I can regenerate the slave with the updated container.
Cheers,
Chris
> Update Container IDs

- src/append_only_data.rs
- src/request.rs
- src/response.rs
Required for maidsafe/safe_client_libs#879
> feat/adata: add GetADataValue request/response types and get_value function for AData enum

- src/append_only_data.rs
- src/request.rs
Required for maidsafe/safe_client_libs#880
> fix/adata: add index fields to AddADataPermissions, SetOwner RPCs and fix indices checking in append functions

- src/mutable_data.rs
Required for maidsafe/safe_client_libs#885
> feat/mdata: add helper function for MData enum to fetch owner field

- src/append_only_data.rs
- src/lib.rs
- src/mutable_data.rs
Do not require to pass the full `Request` struct to derive the required permissions to execute an action.
> Refactor permissions handling

- src/lib.rs
When a vault sends a `Challenge::Request` to a client/app it needs to include its `PublicId` in order to allow the client/app to make an association between that ID and the vault's `SocketAddr`.
> chore/lib: update Challenge::Request

- Jenkinsfile
- Makefile
Hi Nikita,
On a master and version change build, this will publish to crates.io. Since there is a restriction on crates.io that you can't delete any crates that are uploaded, I done the work for this using a sample library that we have.
Here are some links that show the process working:
* [These](https://crates.io/crates/jenkins_sample_lib) crates were published for the sample project.
* [Here](https://jenkins.maidsafe.net/blue/organizations/jenkins/pipeline-sandbox/detail/pipeline-sandbox/3/pipeline) is the build that produced version 0.0.3.
* [Here](https://github.com/maidsafe/jenkins_sample_lib/blob/master/Jenkinsfile) is the Jenkinsfile for the sample lib project. You can see that the code is the same (other than for retrieving build artifacts on the deploy stage, but we don't …
> Publish to crates.io

- src/mutable_data.rs
- Implements `From` trait for SeqEntryActions (from `BTreeMap<Vec<u8>,SeqEntryAction>`)
- Implements getter function for `actions` field in SeqEntryActions
> feat/mdata: impl helpers for MData SeqEntryActions

- Jenkinsfile
Hi Nikita,
We tested a real deployment with safe-cli yesterday and there's a small change here we discovered is necessary for detecting the version change commit.
Cheers,
Chris
> Fix Deployment from Master

- Jenkinsfile
It turns out we can use the `--no-merges` option to remove the merge
related commits. This is a much nicer solution.
> Filter Commits for Deployment

- src/append_only_data.rs
- src/lib.rs
- src/mutable_data.rs
- src/request.rs
Move the following functions from SCL:
1. `request_is_get` (renamed to `Request::get_type`)
2. ~`check_is_owner_adata`~ (already existed as `AData::check_is_last_owner`)
3. `check_perms_adata`
4. `check_perms_mdata`
> refactor/all: move functions to safe-nd

- src/lib.rs
Required for maidsafe/safe_client_libs#989 and maidsafe/safe_client_libs#990
- Adds `allow_mutations` and `get_balance` booleans to `AppPermissions`
> refactor/permission: granularize AppPermissions struct
