maidsafe/safe-nd

Cargo.toml, src/immutable_data.rs, src/lib.rs, src/request.rs
Part 1 of https://github.com/maidsafe/safe_client_libs/issues/809
=> Move ImmutableData from routing to safe-nd

Cargo.toml, src/errors.rs, src/lib.rs, src/mutable_data.rs, src/request.rs, src/response.rs
- Implement published and unpublished mutable data structs as per the RFC
- Introduce `DataError` and `EntryError` enums
- Implement `Debug` trait for `Request` and `Response` enums
=> Proper implementation of the mutable data struct

src/mutable_data.rs
- Introduce a MutableData trait that implements common functions for
sequenced and unsequenced types
- Implement the trait for SeqMutableData and UnseqMutableData using a
macro
=> Introduce MutableData trait

src/immutable_data.rs
Fixes https://github.com/maidsafe/safe_client_libs/issues/828
=> refactor/idata: calculate name when creating new unpublished idata

Cargo.toml, src/coins.rs, src/errors.rs, src/lib.rs, src/request.rs, src/response.rs
This PR adds RPCs and structures required for the Safecoin implementation.
Co-authored by @Fraser999 and @jeanphilippeD.
=> Add Safecoin definitions

Cargo.toml, src/appendable_data.rs, src/lib.rs, src/mutable_data.rs, src/request.rs, src/response.rs
This PR contains rebased changes from #21 and changes from @Yoga07 's fork.
It has all changes required for proper working of the `experimental` branch in SCL.
=> Integrated changes

Cargo.toml, src/appendable_data.rs, src/identity/app.rs, src/identity/client.rs, src/identity/node.rs, src/public_key.rs, src/request.rs, src/response.rs
And also make several required changes for SCL.
`threshold_crypto` temporarily points to a fork until this PR is merged: https://github.com/poanetwork/threshold_crypto/pull/85
=> feat/identity: impl Copy trait for PublicKey

src/identity/app.rs, src/identity/client.rs, src/lib.rs, src/mutable_data.rs
- Add functions to create App and Client identities with the provided
keys
- Verify signatures for both owner and application requests
=> Add functions for identities and refactor mutable data permission handling

src/mutable_data.rs, src/request.rs
Changes for maidsafe/safe_client_libs#841 in SCL
=> fix/mdata: implement constructor and default trait for Mutable Data Seq/Unseq Entry actions

src/immutable_data.rs, src/public_key.rs
Fixes maidsafe/safe_client_libs#882
=> fix/idata: make unpub idata owner field use safe-nd PublicKey

src/errors.rs, src/lib.rs, src/request.rs, src/response.rs, src/transaction.rs
Modify the requests/responses around coin transaction:
1. Remove `GetTransaction` request and response
2. Add `Transaction` response
3. Add `BalanceExists` error variant
Also optimize `Response` debug impl to avoid unnecessary allocation and make the code more readable by utilizing match ergonomics.
=> Change the coin transactions API

src/errors.rs
See https://github.com/maidsafe/safe_client_libs/issues/883
=> chore/errors: remove UnexpectedDataReturned error variant

src/append_only_data.rs, src/errors.rs, src/lib.rs
Resolves maidsafe/safe_client_libs#875
=> fix/adata: fix pushing duplicate entries in AppendOnly Data

Makefile
For some reason I forgot to add this during the initial work.
Need it now for doing these builds from Jenkins.
=> Push Container Target

src/mutable_data.rs
Also optimise the `check_permission` function (taking the `Request` as a reference instead of moving the value).
=> Add helpers in the MData enum

src/mutable_data.rs
Another quick addition to the MData proxy enum.
=> Add user permission helpers in the MData enum

src/mutable_data.rs
=> fix/value: remove unsafe `unwrap` and reimplement Debug for Value

Cargo.toml, Dockerfile.build, Makefile, src/append_only_data.rs, src/coins.rs, src/errors.rs, src/identity/app.rs, src/identity/client.rs, src/identity/mod.rs, src/identity/node.rs, src/immutable_data.rs, src/lib.rs, src/mutable_data.rs, src/public_key.rs, src/request.rs, src/request/account_data.rs, src/request/login_packet.rs, src/response.rs, src/transaction.rs, src/utils.rs
Updates the stable branch with the latest features and fixes.
=> Updates to the stable branch

src/append_only_data.rs, src/request/login_packet.rs
This PR contain one change per commit (more or less). The commit messages explain each change in more details.
=> Various append-only data improvements

src/lib.rs
Needed for maidsafe/safe_vault#746
=> Add Message::Notification

src/append_only_data.rs, src/coins.rs, src/errors.rs, src/identity/app.rs, src/identity/client.rs, src/identity/mod.rs, src/identity/node.rs, src/immutable_data.rs, src/lib.rs, src/mutable_data.rs, src/public_key.rs, src/request.rs, src/request/login_packet.rs, src/response.rs, src/transaction.rs, src/utils.rs
Fixes https://github.com/maidsafe/safe_client_libs/issues/954
=> doc/all: add missing documentation

src/request.rs
required for maidsafe/safe_vault#804
=> Refactor the error_response function

src/lib.rs
Address https://github.com/maidsafe/safe_vault/issues/893
- Expand `Challenge::Response` with an option to request section information from any node.
- Add a new message type, `Message::SectionInfo`, which can be used by Vaults to send the
elders connection information to clients.
- Add `safe_nd::ConnectionInfo` type.
=> Add message types for elders connection info request
